# Generated by Django 5.2.8 on 2026-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk', '0002_rename_ticket_reply_tickets_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tittle',
            new_name='title',
        ),
    ]
