# Generated by Django 5.2.9 on 2025-12-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_updated_at_alter_todo_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todoitem',
        ),
    ]
