# Generated by Django 5.2.8 on 2026-01-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=30)),
                ('Book', models.CharField(max_length=50)),
                ('Member', models.CharField(max_length=50)),
                ('Catagory', models.CharField(max_length=50)),
                ('Loan', models.IntegerField()),
            ],
        ),
    ]
