# Generated by Django 5.2.8 on 2026-01-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_author_book_catagory_loan_members_delete_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
