# Generated by Django 5.2.8 on 2026-02-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_favourotepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAvourotepost',
            new_name='favouritepost',
        ),
    ]
