# Generated by Django 5.2.8 on 2026-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availableBooks',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
