# Generated by Django 5.2.8 on 2026-02-03 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_book_availablebooks_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='returnDate',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loanDate',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='School.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='School.members'),
        ),
    ]
