# Generated by Django 5.2.8 on 2026-02-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAvourotepost',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'post', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.user')),
            ],
        ),
    ]
