# Generated by Django 5.2.8 on 2026-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='ticket',
            new_name='tickets',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
